"use client";

import { isRequestCurrent } from "@/lib/request-freshness";
import Link from "next/link";
import RequestServiceDetails from "@/app/requests/request-service-details";
import { hasAirTravel, requestTitle } from "@/lib/service-request";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import AppShell from "@/app/dashboard/components/app-shell";
import OfferForm from "@/app/offers/offer-form";
import { createOffer, listIncomingOffers, listMyOffers, updateOffer, withdrawOffer, type OfferPayload, type OfferRecord } from "@/app/offers/offers-api";
import { getStoredSession, type AuthSession } from "@/lib/supabase-auth";
import { useUiSettings } from "@/lib/ui-settings";
import { formatAirline } from "@/data/airlines";
import { listRequests, type RequestRecord, type RequestStatus } from "@/app/requests/requests-api";

const categories = ["Aviachipta", "Tur paket", "Mehmonxona", "Transfer", "Gid", "Viza", "Boshqa"];
const categoryRu: Record<string, string> = { Aviachipta: "Авиабилет", "Tur paket": "Турпакет", Mehmonxona: "Отель", Transfer: "Трансфер", Gid: "Гид", Viza: "Виза", Boshqa: "Другое" };
type Tab = "market" | "my-requests" | "my-offers" | "incoming-offers";
const tr = (isRu: boolean, uz: string, ru: string) => isRu ? ru : uz;
const cat = (value: string | null | undefined, isRu: boolean) => value ? (isRu ? categoryRu[value] || value : value) : tr(isRu, "Kategoriya ko‘rsatilmagan", "Категория не указана");

function isTab(value: string | null): value is Tab { return value === "market" || value === "my-requests" || value === "my-offers" || value === "incoming-offers"; }
function formatDate(value: string | null, isRu: boolean) {
  if (!value) return tr(isRu, "Sana ko‘rsatilmagan", "Дата не указана");
  return new Intl.DateTimeFormat(isRu ? "ru-RU" : "uz-UZ", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));
}
function requestStatusLabel(status: RequestStatus | "all", isRu: boolean) {
  const uz: Record<RequestStatus | "all", string> = { all: "Barcha statuslar", open: "Ochiq", accepted: "Qabul qilingan", closed: "Yopilgan", cancelled: "Bekor qilingan" };
  const ru: Record<RequestStatus | "all", string> = { all: "Все статусы", open: "Открыт", accepted: "Принят", closed: "Закрыт", cancelled: "Отменён" };
  return isRu ? ru[status] : uz[status];
}
function offerStatusLabel(status: OfferRecord["status"], isRu: boolean) {
  const uz = { pending: "Kutilmoqda", accepted: "Qabul qilingan", rejected: "Rad etilgan", withdrawn: "Qaytarib olingan" } as const;
  const ru = { pending: "Ожидает", accepted: "Принято", rejected: "Отклонено", withdrawn: "Отозвано" } as const;
  return isRu ? ru[status] : uz[status];
}

function MarketRequestCard({ request, isOwner, isFormOpen, hasOffered, offerMessage, onToggleForm, onSubmitOffer, isRu }: {
  request: RequestRecord; isOwner: boolean; isFormOpen: boolean; hasOffered: boolean; offerMessage: string; onToggleForm: () => void; onSubmitOffer: (payload: OfferPayload) => Promise<void>; isRu: boolean;
}) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
    <Link href={`/requests/${request.id}`} className="block rounded-xl focus:outline-none focus:ring-4 focus:ring-blue-100">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold text-[#0b1f3a]">{requestTitle(request)}</h2>{isOwner && <span className="rounded-full bg-cyan-50 px-2.5 py-1 text-[11px] font-bold text-cyan-700">{tr(isRu,"Mening so‘rovim","Мой запрос")}</span>}</div><p className="mt-2 text-sm text-slate-500">{cat(request.category,isRu)} · {formatDate(request.travel_date,isRu)}</p></div><span className="w-fit rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{isRequestCurrent(request) ? tr(isRu,"Ochiq","Открыт") : tr(isRu,"Muddati o‘tgan","Истёк")}</span></div>
    <RequestServiceDetails request={request} compact />
      <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-slate-400"><span>{request.creator?.full_name || tr(isRu,"Agent nomi ko‘rsatilmagan","Имя агента не указано")}</span><span>{request.creator?.company_name || tr(isRu,"Kompaniya ko‘rsatilmagan","Компания не указана")}</span><span>{request.creator?.city || tr(isRu,"Shahar ko‘rsatilmagan","Город не указан")}</span>{request.creator?.is_verified && <span className="font-semibold text-blue-600">{tr(isRu,"Tasdiqlangan agent","Проверенный агент")}</span>}<span className="sm:ml-auto">{tr(isRu,"Yaratilgan","Создан")}: {formatDate(request.created_at,isRu)}</span></div>
    </Link>
    {!isOwner && isRequestCurrent(request) && <div className="mt-5 flex flex-wrap items-center gap-3 border-t border-slate-100 pt-4">{offerMessage ? <p role="status" className="rounded-xl bg-emerald-50 px-4 py-2.5 text-sm font-semibold text-emerald-700">{offerMessage}</p> : hasOffered ? <span className="rounded-xl bg-slate-100 px-4 py-2.5 text-sm font-semibold text-slate-500">{tr(isRu,"Taklif yuborilgan","Предложение отправлено")}</span> : <button type="button" onClick={onToggleForm} className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700 focus:outline-none focus:ring-4 focus:ring-blue-100">{isFormOpen ? tr(isRu,"Formani yopish","Закрыть форму") : tr(isRu,"Taklif berish","Дать предложение")}</button>}</div>}
    {!isOwner && isRequestCurrent(request) && isFormOpen && !hasOffered && !offerMessage && <div className="mt-5 rounded-2xl border border-blue-100 bg-blue-50/60 p-4 sm:p-5"><OfferForm category={request.category} serviceDetails={request.service_details} submitLabel={tr(isRu,"Taklif yuborish","Отправить предложение")} submittingLabel={tr(isRu,"Yuborilmoqda...","Отправка...")} onSubmit={onSubmitOffer} /></div>}
  </div>;
}

function MyRequestCard({ request, offersCount, isRu }: { request: RequestRecord; offersCount: number; isRu: boolean }) {
  const statusClass = request.status === "open" ? "bg-emerald-50 text-emerald-700" : request.status === "cancelled" ? "bg-red-50 text-red-700" : "bg-slate-100 text-slate-600";
  return <Link href={`/requests/${request.id}`} className="block rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md focus:outline-none focus:ring-4 focus:ring-blue-100">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold text-[#0b1f3a]">{requestTitle(request)}</h2><span className="rounded-full bg-cyan-50 px-2.5 py-1 text-[11px] font-bold text-cyan-700">{tr(isRu,"Mening so‘rovim","Мой запрос")}</span></div><p className="mt-2 text-sm text-slate-500">{cat(request.category,isRu)} · {formatDate(request.travel_date,isRu)}</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-semibold ${statusClass}`}>{request.status === "open" && !isRequestCurrent(request) ? tr(isRu,"Muddati o‘tgan","Истёк") : requestStatusLabel(request.status,isRu)}</span></div>
    <RequestServiceDetails request={request} compact />
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><span className="text-xs text-slate-400">{tr(isRu,"Yaratilgan","Создан")}: {formatDate(request.created_at,isRu)}</span><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{offersCount} {tr(isRu,"ta taklif keldi","предложений")}</span></div>
  </Link>;
}

function MyOfferCard({ offer, onEdit, onWithdraw, isRu }: { offer: OfferRecord; onEdit: (offer: OfferRecord) => void; onWithdraw: (offer: OfferRecord) => void; isRu: boolean }) {
  const statusClass = offer.status === "pending" ? "bg-amber-50 text-amber-700" : offer.status === "accepted" ? "bg-emerald-50 text-emerald-700" : offer.status === "rejected" ? "bg-red-50 text-red-700" : "bg-slate-100 text-slate-600";
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><Link href={`/requests/${offer.request_id}`} className="text-lg font-semibold text-[#0b1f3a] hover:text-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500">{requestTitle(offer.request || {})}</Link><p className="mt-2 text-sm text-slate-500">{cat(offer.request?.category,isRu)} · {formatDate(offer.request?.travel_date || null,isRu)}</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-semibold ${statusClass}`}>{offerStatusLabel(offer.status,isRu)}</span></div><div className="mt-5 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2"><p className="text-xl font-semibold text-[#0b1f3a]">{offer.price == null ? tr(isRu,"Narx ko‘rsatilmagan","Цена не указана") : `${offer.price.toLocaleString(isRu ? "ru-RU" : "uz-UZ")} ${offer.currency}`}</p>{hasAirTravel(offer.request || {}) && <><p className="text-sm text-slate-500">{tr(isRu,"Aviakompaniya","Авиакомпания")}: {formatAirline(offer.airline)}</p><p className="text-sm text-slate-500">{tr(isRu,"Bagaj","Багаж")}: {offer.baggage || tr(isRu,"Ko‘rsatilmagan","Не указан")}</p></>}{offer.comment && <p className="text-sm text-slate-500 sm:col-span-2">{offer.comment}</p>}</div><p className="mt-4 text-xs text-slate-400">{formatDate(offer.created_at,isRu)}</p>{offer.status === "pending" && <div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={() => onEdit(offer)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:border-blue-300 hover:text-blue-700">{tr(isRu,"Tahrirlash","Редактировать")}</button><button type="button" onClick={() => onWithdraw(offer)} className="rounded-xl border border-amber-200 px-4 py-2.5 text-sm font-semibold text-amber-700 hover:bg-amber-50">{tr(isRu,"Taklifni qaytarib olish","Отозвать предложение")}</button></div>}</article>;
}

function IncomingOfferCard({ offer, isRu }: { offer: OfferRecord; isRu: boolean }) {
  const statusClass = offer.status === "pending" ? "bg-amber-50 text-amber-700" : offer.status === "accepted" ? "bg-emerald-50 text-emerald-700" : offer.status === "rejected" ? "bg-red-50 text-red-700" : "bg-slate-100 text-slate-600";
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-lg font-semibold text-[#0b1f3a]">{requestTitle(offer.request || {})}</p><p className="mt-2 text-sm text-slate-500">{cat(offer.request?.category,isRu)} · {formatDate(offer.request?.travel_date || null,isRu)}</p><p className="mt-2 text-sm text-slate-500">{offer.agent?.full_name || tr(isRu,"Agent nomi ko‘rsatilmagan","Имя агента не указано")} · {offer.agent?.company_name || tr(isRu,"Kompaniya ko‘rsatilmagan","Компания не указана")}</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-semibold ${statusClass}`}>{offerStatusLabel(offer.status,isRu)}</span></div><div className="mt-5 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2"><p className="text-xl font-semibold text-[#0b1f3a]">{offer.price == null ? tr(isRu,"Narx ko‘rsatilmagan","Цена не указана") : `${offer.price.toLocaleString(isRu ? "ru-RU" : "uz-UZ")} ${offer.currency}`}</p>{hasAirTravel(offer.request || {}) && <><p className="text-sm text-slate-500">{tr(isRu,"Aviakompaniya","Авиакомпания")}: {formatAirline(offer.airline)}</p><p className="text-sm text-slate-500">{tr(isRu,"Bagaj","Багаж")}: {offer.baggage || tr(isRu,"Ko‘rsatilmagan","Не указан")}</p></>}{offer.comment && <p className="text-sm text-slate-500 sm:col-span-2">{offer.comment}</p>}</div><Link href={`/requests/${offer.request_id}`} className="mt-5 inline-flex rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:border-blue-300 hover:text-blue-700">{tr(isRu,"So‘rovni ko‘rish","Открыть запрос")}</Link></article>;
}

export default function RequestsPage() {
  const router = useRouter();
  const { isRu } = useUiSettings();
  const [session, setSession] = useState<AuthSession | null>(null);
  const [tab, setTab] = useState<Tab>("market");
  const tabs: { id: Tab; label: string }[] = isRu ? [
    { id: "market", label: "Рынок" }, { id: "my-requests", label: "Мои запросы" }, { id: "my-offers", label: "Мои предложения" }, { id: "incoming-offers", label: "Входящие предложения" },
  ] : [
    { id: "market", label: "Bozor" }, { id: "my-requests", label: "Mening so‘rovlarim" }, { id: "my-offers", label: "Mening takliflarim" }, { id: "incoming-offers", label: "Menga kelgan takliflar" },
  ];

  const [marketPage, setMarketPage] = useState(0); const [myPage, setMyPage] = useState(0);
  const [marketFreshness, setMarketFreshness] = useState<"current" | "expired">("current");
  const [marketRequests, setMarketRequests] = useState<RequestRecord[]>([]); const [marketCategory, setMarketCategory] = useState(""); const [marketSearch, setMarketSearch] = useState(""); const [isMarketLoading, setIsMarketLoading] = useState(true); const [marketError, setMarketError] = useState("");
  const [myRequests, setMyRequests] = useState<RequestRecord[]>([]); const [myStatus, setMyStatus] = useState<RequestStatus | "all">("all"); const [myCategory, setMyCategory] = useState(""); const [mySearch, setMySearch] = useState(""); const [isMyRequestsLoading, setIsMyRequestsLoading] = useState(true); const [myRequestsError, setMyRequestsError] = useState("");
  const [myOffers, setMyOffers] = useState<OfferRecord[]>([]); const [isMyOffersLoading, setIsMyOffersLoading] = useState(true); const [myOffersError, setMyOffersError] = useState(""); const [editingOffer, setEditingOffer] = useState<OfferRecord | null>(null);
  const [incomingOffers, setIncomingOffers] = useState<OfferRecord[]>([]); const [isIncomingLoading, setIsIncomingLoading] = useState(true); const [incomingError, setIncomingError] = useState("");
  const [openOfferRequestId, setOpenOfferRequestId] = useState<string | null>(null); const [offeredRequestIds, setOfferedRequestIds] = useState<Set<string>>(new Set()); const [offerSuccessId, setOfferSuccessId] = useState<string | null>(null);

  useEffect(() => { const storedSession = getStoredSession(); if (!storedSession) { window.location.replace("/login"); return; } const timeoutId = window.setTimeout(() => { setSession(storedSession); const params = new URLSearchParams(window.location.search); const urlTab = params.get("tab"); if (isTab(urlTab)) setTab(urlTab); const requestId = params.get("request_id"); if (requestId) setOpenOfferRequestId(requestId); }, 0); return () => window.clearTimeout(timeoutId); }, []);
  function changeTab(nextTab: Tab) { setTab(nextTab); router.replace(`/requests?tab=${nextTab}`); }

  useEffect(() => { if (!session || tab !== "market") return; let active = true; const timeoutId = window.setTimeout(() => { setIsMarketLoading(true); setMarketError(""); listRequests({ status: "open", category: marketCategory, search: marketSearch, freshness: marketFreshness, offset: marketPage * 20 }).then((rows) => { if (active) setMarketRequests(rows); }).catch((requestError: unknown) => { if (requestError instanceof Error && (requestError.message === "AUTH_SESSION_EXPIRED" || requestError.message === "AUTH_SESSION_MISSING")) { window.location.replace("/login"); return; } if (active) setMarketError(tr(isRu,"So‘rovlarni yuklashda xatolik yuz berdi. Qayta urinib ko‘ring.","Не удалось загрузить запросы. Попробуйте ещё раз.")); }).finally(() => { if (active) setIsMarketLoading(false); }); }, 350); return () => { active = false; window.clearTimeout(timeoutId); }; }, [session, tab, marketCategory, marketSearch, marketFreshness, marketPage, isRu]);
  useEffect(() => { if (!session || tab !== "market") return; const timeoutId = window.setTimeout(() => { listMyOffers().then((offers) => setOfferedRequestIds(new Set(offers.filter((offer) => offer.status !== "withdrawn").map((offer) => offer.request_id)))).catch(() => undefined); }, 0); return () => window.clearTimeout(timeoutId); }, [session, tab]);
  useEffect(() => { if (!session || tab !== "my-requests") return; let active = true; const timeoutId = window.setTimeout(() => { setIsMyRequestsLoading(true); setMyRequestsError(""); listRequests({ status: myStatus, category: myCategory, search: mySearch, createdBy: session.user.id, offset: myPage * 20 }).then((rows) => { if (active) setMyRequests(rows); }).catch((requestError: unknown) => { if (requestError instanceof Error && (requestError.message === "AUTH_SESSION_EXPIRED" || requestError.message === "AUTH_SESSION_MISSING")) { window.location.replace("/login"); return; } if (active) setMyRequestsError(tr(isRu,"So‘rovlarni yuklashda xatolik yuz berdi. Qayta urinib ko‘ring.","Не удалось загрузить запросы. Попробуйте ещё раз.")); }).finally(() => { if (active) setIsMyRequestsLoading(false); }); }, 350); return () => { active = false; window.clearTimeout(timeoutId); }; }, [session, tab, myStatus, myCategory, mySearch, myPage, isRu]);
  useEffect(() => { if (!session || (tab !== "my-requests" && tab !== "incoming-offers")) return; const timeoutId = window.setTimeout(() => { setIsIncomingLoading(true); setIncomingError(""); listIncomingOffers().then(setIncomingOffers).catch((requestError: unknown) => { if (requestError instanceof Error && (requestError.message === "AUTH_SESSION_EXPIRED" || requestError.message === "AUTH_SESSION_MISSING")) { window.location.replace("/login"); return; } setIncomingError(tr(isRu,"Takliflarni yuklashda xatolik yuz berdi. Qayta urinib ko‘ring.","Не удалось загрузить предложения. Попробуйте ещё раз.")); }).finally(() => setIsIncomingLoading(false)); }, 0); return () => window.clearTimeout(timeoutId); }, [session, tab, isRu]);
  useEffect(() => { if (!session || tab !== "my-offers") return; const timeoutId = window.setTimeout(() => { setIsMyOffersLoading(true); setMyOffersError(""); listMyOffers().then(setMyOffers).catch((requestError: unknown) => { if (requestError instanceof Error && (requestError.message === "AUTH_SESSION_EXPIRED" || requestError.message === "AUTH_SESSION_MISSING")) { window.location.replace("/login"); return; } setMyOffersError(tr(isRu,"Takliflarni yuklashda xatolik yuz berdi. Qayta urinib ko‘ring.","Не удалось загрузить предложения. Попробуйте ещё раз.")); }).finally(() => setIsMyOffersLoading(false)); }, 0); return () => window.clearTimeout(timeoutId); }, [session, tab, isRu]);

  async function submitMarketOffer(requestId: string, payload: OfferPayload) { try { await createOffer(requestId, payload); setOfferedRequestIds((current) => new Set(current).add(requestId)); setOfferSuccessId(requestId); } catch (submitError) { if (submitError instanceof Error && submitError.message === "SUPABASE_409") throw new Error(tr(isRu,"Bu so‘rov uchun avval taklif yuborgansiz.","Вы уже отправляли предложение на этот запрос.")); throw new Error(tr(isRu,"Taklifni yuborib bo‘lmadi. Ma’lumotlarni tekshirib, qayta urinib ko‘ring.","Не удалось отправить предложение. Проверьте данные и попробуйте снова.")); } }
  async function submitEdit(payload: OfferPayload) { if (!editingOffer || editingOffer.status !== "pending") return; const updated = await updateOffer(editingOffer.id, payload); if (!updated) throw new Error(tr(isRu,"Faqat kutilayotgan taklifni tahrirlash mumkin.","Редактировать можно только ожидающее предложение.")); setMyOffers((current) => current.map((offer) => offer.id === updated.id ? { ...offer, ...updated } : offer)); setEditingOffer(null); }
  async function handleWithdraw(offer: OfferRecord) { if (offer.status !== "pending" || !window.confirm(tr(isRu,"Taklifni qaytarib olishga ishonchingiz komilmi?","Отозвать предложение?"))) return; try { const updated = await withdrawOffer(offer.id); if (updated) setMyOffers((current) => current.map((item) => item.id === offer.id ? { ...item, ...updated } : item)); } catch { setMyOffersError(tr(isRu,"Taklifni qaytarib olib bo‘lmadi.","Не удалось отозвать предложение.")); } }

  const offerCountByRequest = incomingOffers.reduce<Record<string, number>>((acc, offer) => { acc[offer.request_id] = (acc[offer.request_id] || 0) + 1; return acc; }, {});
  const pendingIncomingCount = incomingOffers.filter((offer) => offer.status === "pending").length;
  function clearMarketFilters() { setMarketPage(0); setMarketCategory(""); setMarketSearch(""); }
  function clearMyFilters() { setMyPage(0); setMyStatus("all"); setMyCategory(""); setMySearch(""); }
  const inputClass = "rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100";

  return <AppShell session={session} activePath="/requests">
    <header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-blue-600">{tr(isRu,"Ish maydoni","РАБОЧАЯ ЗОНА")}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-[#0b1f3a]">{tr(isRu,"So‘rovlar va takliflar","Запросы и предложения")}</h1><p className="mt-2 text-sm text-slate-500">{tr(isRu,"Agentlar so‘rovlarini ko‘ring, taklif yuboring va kelgan takliflarni boshqaring.","Просматривайте запросы агентов, отправляйте предложения и управляйте входящими предложениями.")}</p></div><Link href="/requests/new" className="w-fit rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700">{tr(isRu,"Yangi so‘rov","Новый запрос")}</Link></header>
    <nav aria-label={tr(isRu,"Ish maydoni bo‘limlari","Разделы рабочей зоны")} className="mt-8 flex flex-wrap gap-2 border-b border-slate-200 pb-3">{tabs.map((item) => <button key={item.id} type="button" onClick={() => changeTab(item.id)} className={`flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold ${tab === item.id ? "bg-blue-600 text-white shadow-sm" : "text-slate-500 hover:bg-slate-100"}`}><span>{item.label}</span>{item.id === "incoming-offers" && pendingIncomingCount > 0 && <span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${tab === item.id ? "bg-white/20 text-white" : "bg-blue-100 text-blue-700"}`}>{pendingIncomingCount}</span>}</button>)}</nav>

    {tab === "market" && <section className="mt-6"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-3 md:grid-cols-[1fr_1.4fr_auto]"><select value={marketCategory} onChange={(event) => { setMarketCategory(event.target.value); setMarketPage(0); }} className={inputClass}><option value="">{tr(isRu,"Barcha kategoriyalar","Все категории")}</option>{categories.map((item) => <option key={item} value={item}>{isRu ? categoryRu[item] : item}</option>)}</select><input value={marketSearch} onChange={(event) => { setMarketSearch(event.target.value); setMarketPage(0); }} placeholder={tr(isRu,"Yo‘nalish yoki xizmat bo‘yicha qidirish","Поиск по маршруту или услуге")} className={inputClass} />{(marketCategory || marketSearch) && <button type="button" onClick={clearMarketFilters} className="rounded-xl px-3 py-2 text-sm font-semibold text-blue-600 hover:bg-blue-50">{tr(isRu,"Filtrni tozalash","Сбросить фильтр")}</button>}</div><label className="mt-3 flex items-center gap-3 text-sm text-slate-600">{tr(isRu,"Ko‘rinish","Показывать")}<select value={marketFreshness} onChange={(event) => { setMarketFreshness(event.target.value as "current" | "expired"); setMarketPage(0); }} className={inputClass}><option value="current">{tr(isRu,"Amaldagi so‘rovlar","Актуальные запросы")}</option><option value="expired">{tr(isRu,"Arxiv — muddati o‘tgan","Архив — истёкшие")}</option></select></label></div>{marketError && <p role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700">{marketError}</p>}{isMarketLoading ? <div className="mt-6 space-y-4"><div className="h-44 animate-pulse rounded-2xl bg-slate-200" /><div className="h-44 animate-pulse rounded-2xl bg-slate-200" /></div> : marketRequests.length ? <div className="mt-6 space-y-4">{marketRequests.map((request) => <MarketRequestCard key={request.id} request={request} isRu={isRu} isOwner={session?.user.id === request.created_by} isFormOpen={openOfferRequestId === request.id} hasOffered={offeredRequestIds.has(request.id)} offerMessage={offerSuccessId === request.id ? tr(isRu,"Taklif yuborildi","Предложение отправлено") : ""} onToggleForm={() => setOpenOfferRequestId((current) => current === request.id ? null : request.id)} onSubmitOffer={(payload) => submitMarketOffer(request.id,payload)} />)}</div> : <div className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><p className="text-lg font-semibold text-[#0b1f3a]">{tr(isRu,"Hozircha ochiq so‘rovlar yo‘q","Пока нет открытых запросов")}</p><p className="mt-2 text-sm text-slate-500">{tr(isRu,"Filtrlarni o‘zgartirib ko‘ring.","Попробуйте изменить фильтры.")}</p></div>}<Pagination page={marketPage} onChange={setMarketPage} hasNext={marketRequests.length === 20} disabled={isMarketLoading} isRu={isRu} /></section>}

    {tab === "my-requests" && <section className="mt-6"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-3 md:grid-cols-[1fr_1fr_1.4fr_auto]"><select value={myStatus} onChange={(event) => { setMyStatus(event.target.value as RequestStatus | "all"); setMyPage(0); }} className={inputClass}>{(["all","open","accepted","closed","cancelled"] as const).map((value) => <option key={value} value={value}>{requestStatusLabel(value,isRu)}</option>)}</select><select value={myCategory} onChange={(event) => { setMyCategory(event.target.value); setMyPage(0); }} className={inputClass}><option value="">{tr(isRu,"Barcha kategoriyalar","Все категории")}</option>{categories.map((item) => <option key={item} value={item}>{isRu ? categoryRu[item] : item}</option>)}</select><input value={mySearch} onChange={(event) => { setMySearch(event.target.value); setMyPage(0); }} placeholder={tr(isRu,"Yo‘nalish yoki xizmat bo‘yicha qidirish","Поиск по маршруту или услуге")} className={inputClass} />{(myStatus !== "all" || myCategory || mySearch) && <button type="button" onClick={clearMyFilters} className="rounded-xl px-3 py-2 text-sm font-semibold text-blue-600 hover:bg-blue-50">{tr(isRu,"Filtrni tozalash","Сбросить фильтр")}</button>}</div></div>{myRequestsError && <p role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700">{myRequestsError}</p>}{isMyRequestsLoading || isIncomingLoading ? <div className="mt-6 space-y-4"><div className="h-44 animate-pulse rounded-2xl bg-slate-200" /><div className="h-44 animate-pulse rounded-2xl bg-slate-200" /></div> : myRequests.length ? <div className="mt-6 space-y-4">{myRequests.map((request) => <MyRequestCard key={request.id} request={request} offersCount={offerCountByRequest[request.id] || 0} isRu={isRu} />)}</div> : <div className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><p className="text-lg font-semibold text-[#0b1f3a]">{tr(isRu,"Hozircha so‘rovlar yo‘q","Пока нет запросов")}</p><p className="mt-2 text-sm text-slate-500">{tr(isRu,"Filtrlarni o‘zgartiring yoki yangi so‘rov yarating.","Измените фильтры или создайте новый запрос.")}</p><Link href="/requests/new" className="mt-6 inline-flex rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white">{tr(isRu,"Yangi so‘rov yaratish","Создать новый запрос")}</Link></div>}<Pagination page={myPage} onChange={setMyPage} hasNext={myRequests.length === 20} disabled={isMyRequestsLoading} isRu={isRu} /></section>}

    {tab === "my-offers" && <section className="mt-6">{editingOffer && <div className="mb-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-semibold text-[#0b1f3a]">{tr(isRu,"Taklifni tahrirlash","Редактировать предложение")}</h2><button type="button" onClick={() => setEditingOffer(null)} className="text-sm font-semibold text-slate-500">{tr(isRu,"Bekor qilish","Отмена")}</button></div><div className="mt-5"><OfferForm category={editingOffer.request?.category} serviceDetails={editingOffer.request?.service_details} initialValues={editingOffer} submitLabel={tr(isRu,"Saqlash","Сохранить")} submittingLabel={tr(isRu,"Saqlanmoqda...","Сохранение...")} onSubmit={submitEdit} /></div></div>}{myOffersError && <p role="alert" className="mb-5 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700">{myOffersError}</p>}{isMyOffersLoading ? <div className="space-y-4"><div className="h-44 animate-pulse rounded-2xl bg-slate-200" /><div className="h-44 animate-pulse rounded-2xl bg-slate-200" /></div> : myOffers.length ? <div className="space-y-4">{myOffers.map((offer) => <MyOfferCard key={offer.id} offer={offer} onEdit={setEditingOffer} onWithdraw={handleWithdraw} isRu={isRu} />)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><p className="text-lg font-semibold text-[#0b1f3a]">{tr(isRu,"Hozircha takliflar yo‘q","Пока нет предложений")}</p><p className="mt-2 text-sm text-slate-500">{tr(isRu,"Bozor bo‘limidan so‘rovlarga taklif yuboring.","Отправляйте предложения на запросы в разделе Рынок.")}</p></div>}</section>}

    {tab === "incoming-offers" && <section className="mt-6">{incomingError && <p role="alert" className="mb-5 rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700">{incomingError}</p>}{isIncomingLoading ? <div className="space-y-4"><div className="h-44 animate-pulse rounded-2xl bg-slate-200" /><div className="h-44 animate-pulse rounded-2xl bg-slate-200" /></div> : incomingOffers.length ? <div className="space-y-4">{incomingOffers.map((offer) => <IncomingOfferCard key={offer.id} offer={offer} isRu={isRu} />)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><p className="text-lg font-semibold text-[#0b1f3a]">{tr(isRu,"Hozircha takliflar yo‘q","Пока нет предложений")}</p><p className="mt-2 text-sm text-slate-500">{tr(isRu,"So‘rovlaringizga takliflar kelganda shu yerda ko‘rinadi.","Предложения на ваши запросы появятся здесь.")}</p></div>}</section>}
  </AppShell>;
}

function Pagination({ page, onChange, hasNext, disabled, isRu }: { page: number; onChange: (page: number) => void; hasNext: boolean; disabled: boolean; isRu: boolean }) {
  return <nav aria-label={tr(isRu,"So‘rovlar sahifalari","Страницы запросов")} className="mt-6 flex items-center justify-center gap-4 text-sm"><button disabled={disabled || page === 0} onClick={() => onChange(page - 1)} className="rounded-lg border border-slate-200 px-4 py-2 disabled:opacity-40">← {tr(isRu,"Oldingi","Назад")}</button><span>{isRu ? `Страница ${page + 1}` : `${page + 1}-sahifa`}</span><button disabled={disabled || !hasNext} onClick={() => onChange(page + 1)} className="rounded-lg border border-slate-200 px-4 py-2 disabled:opacity-40">{tr(isRu,"Keyingi","Далее")} →</button></nav>;
}
